;[
  {
    createdAt: '2026-02-08T12:34:25.975Z',
    updatedAt: '2026-02-08T12:34:25.975Z',
    name: 'Chemiz (M) Sdn Bhd',
    details: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Production Manager at Chemiz (M) Sdn Bhd, leading the development and implementation of ISO 9001, ISO 19001, and ISO 13485 standards to ensure compliance with international quality management practices. Spearheaded the integration of cloud-based storage solutions, improving data management and reducing reliance on physical documentation. Directed production teams in maintaining the highest quality assurance standards, while driving cost-effective operational improvements and leading new product development initiatives in Lab (Formulations) operations.',
                type: 'text',
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: null,
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    yearRange: 'September 2020 - April 2024',
    position: 'Production Manager',
    ctaHref: '/experiences/chemiz',
    companyImage: '69883f78743475506046e3ed',
    projects: [],
    id: '698882d1247da53dc00fd902',
  },
  {
    createdAt: '2026-02-08T12:32:48.555Z',
    updatedAt: '2026-02-08T12:32:48.555Z',
    name: 'Bateriku (M) Sdn Bhd',
    details: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'As a Software Engineer/Developer at Bateriku (M) Sdn Bhd, I was responsible for maintaining backend systems using Ruby on Rails, ensuring high performance and reliability. My active participation in the full development lifecycle, from planning to deployment, helped streamline workflows and accelerate delivery timelines',
                type: 'text',
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: null,
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    yearRange: 'April 2024 - May 2024',
    position: 'Software Engineer',
    ctaHref: '/experiences/bateriku',
    companyImage: '69883f90743475506046e40d',
    projects: [],
    id: '69888270247da53dc00fd8c2',
  },
  {
    createdAt: '2026-02-08T12:31:56.500Z',
    updatedAt: '2026-02-08T12:31:56.500Z',
    name: 'GovTech Nucleus Unit (GNU)',
    details: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Full-Stack Engineer at GNU, responsible for developing, deploying, and maintaining scalable web and mobile applications for the public sector. Focused on creating industry-standard solutions to improve accessibility, efficiency, and user engagement in public services. Collaborated with cross-functional teams to drive innovation and ensure the delivery of high-quality software solutions.',
                type: 'text',
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: null,
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    yearRange: 'May 2024 - Present',
    position: 'Software Engineer',
    ctaHref: '/experiences/govtech',
    companyImage: '69883f5b743475506046e3b3',
    projects: [],
    id: '6988823c247da53dc00fd883',
  },
]
